server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
##eureka server 启用安全验证
security:
  basic:
    enabled: true
  user:
    name: ggg
    password: gggggg