spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/one
    username: root
    password: 12345
  application:
    name: info-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
